{
    'name': 'Odoo Library Management System',
    'version': '1.0',
    'summary': 'Complete books management library system',
    'sequence': 1,
    'description': "It is a simple library management system.",
    'category': 'Education/Library',
    'author': 'Erotocaap Software Pvt. Ltd.',
    'website': 'https://www.erotocaap.com',
    'license': 'OPL-1',
    'support': 'support@erotoca.com',
    'images': [
        'static/description/banner.gif',   # primary banner shown on App Store listing
        'static/description/icon.png',      # 256×256 module icon (listing thumbnail)
        'static/description/screenshot1.png',
        'static/description/screenshot2.png',
        'static/description/screenshot3.png',
    ],
    'depends': ['base', 'mail'],
    'assets': {
        'web.assets_backend': [
            'wk_library_management/static/src/js/dashboard.js',
            'wk_library_management/static/src/xml/dashboard.xml',
            'wk_library_management/static/src/scss/dashboard.scss',
        ]
    },
    'data': [
        'security/library_security.xml',
        'security/library_record_rule.xml',
        'security/ir.model.access.csv',
        'views/booking_sequence.xml',
        'reports/book_report.xml',
        'reports/book_report_template.xml',
        'views/book_views.xml',
        'views/category_views.xml',
        'reports/booking_report_template.xml',
        'reports/booking_report.xml',
        'reports/partner_booking_report.xml',
        'reports/partner_booking_report_template.xml',
        'views/booking_views.xml',
        'data/mail_template.xml',
        'data/mail_template_remindar.xml',
        'views/res_partner_view.xml',
        'wizard/book_request_issue_wizard.xml',
        'wizard/wizard_first_view.xml',
        'wizard/update_booking_wizard_view.xml',
        'views/members_view.xml',
        'data/server_action.xml',
        'views/dashboard_action.xml',
        'views/menu_views.xml',
        'demo1/book_demo.xml',
        'demo1/library_category_demo.xml',
    ],
    'demo': [
        'demo/demo_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}